# Tests generated by ChatGPT. Do not edit manually.
# Not checked for correctness.

import numpy as np

from impulso import (
    Circuit,
    Resistor,
    Capacitor,
    Inductor,
    Opamp,
    DCVoltageSource,
    DCCurrentSource,
    SinusoidalCurrentSource,
    Diode,
    Wire,
    VCCS,
    VCVS,
    CCCS,
    CCVS,
    solve_dc,
)


def close(value, expected, tol=1e-3):
    return np.isclose(value, expected, rtol=tol, atol=tol)


class Test_DC:

    def test_illegal_component_values_are_rejected(self):
        try:
            Resistor(-1)
            assert False
        except AssertionError:
            assert True

        try:
            Capacitor(-1)
            assert False
        except AssertionError:
            assert True

        try:
            Inductor(-1)
            assert False
        except AssertionError:
            assert True

    def test_illegal_topology_is_caught(self):
        circuit = Circuit()
        V1 = DCVoltageSource(1, id='V1')
        R1 = Resistor(1e3, id='R1')
        circuit.add(V1, [0, 1])
        circuit.add(R1, [2, 3])
        try:
            solve_dc(circuit)
            assert False
        except Exception:
            assert True

    def test_resistor_wire_voltage_and_current_directions(self):
        circuit = Circuit()
        V1 = DCVoltageSource(1, id='V1')
        W1 = Wire(id='W1')
        R1 = Resistor(1e3, id='R1')

        circuit.add(V1, [0, 1])
        circuit.add(W1, [1, 2])
        circuit.add(R1, [2, 0])

        voltages, currents = solve_dc(circuit)

        assert close(voltages[1], 1.0)
        assert close(voltages[2], 1.0)
        assert close(currents[R1], 0.001)
        assert close(currents[W1], -0.001)
        assert close(currents[V1], 0.001)

    def test_capacitor_and_inductor_dc_behavior(self):
        circuit = Circuit()
        V1 = DCVoltageSource(1, id='V1')
        R1 = Resistor(1e3, id='R1')
        L1 = Inductor(1e-3, id='L1')
        C1 = Capacitor(1e-6, id='C1')

        circuit.add(V1, [0, 1])
        circuit.add(R1, [1, 2])
        circuit.add(L1, [2, 0])
        circuit.add(C1, [2, 0])

        voltages, currents = solve_dc(circuit)

        assert close(voltages[2], 0.0)
        assert close(currents[C1], 0.0)
        assert close(currents[R1], 0.001)
        assert close(currents[L1], 0.001)

    def test_dccurrent_source_direction(self):
        circuit = Circuit()
        I1 = DCCurrentSource(0.001, id='I1')
        R1 = Resistor(1e3, id='R1')

        circuit.add(I1, [1, 0])
        circuit.add(R1, [1, 0])

        voltages, currents = solve_dc(circuit)

        assert close(voltages[1], -1.0)
        assert close(currents[R1], -0.001)
        assert close(currents[I1], 0.001)

    def test_vcvs_voltage_gain_in_dc(self):
        circuit = Circuit()
        V1 = DCVoltageSource(1, id='V1')
        R1 = Resistor(1e3, id='R1')
        R2 = Resistor(1e3, id='R2')
        E1 = VCVS(2, id='E1')

        circuit.add(V1, [0, 1])
        circuit.add(R1, [1, 0])
        circuit.add(E1, [2, 0, 1, 0])
        circuit.add(R2, [2, 0])

        voltages, currents = solve_dc(circuit)

        assert close(voltages[2], 2.0)
        assert close(currents[R2], 0.002)
        assert close(currents[E1], -0.002)

    def test_cccs_and_ccvs_current_direction(self):
        circuit = Circuit()
        I1 = DCCurrentSource(1, id='I1')
        I2 = DCCurrentSource(3, id='I2')
        R1 = Resistor(1e3, id='R1')
        R2 = Resistor(1e3, id='R2')
        R3 = Resistor(1e3, id='R3')
        R4 = Resistor(1e3, id='R4')
        V1 = DCVoltageSource(0, id='V1')
        CCCS1 = CCCS(A=3, id='CCCS1')

        circuit.add(I1, [0, 1])
        circuit.add(R1, [1, 0])
        circuit.add(CCCS1, [1, 2])
        circuit.add(R2, [2, 0])
        circuit.add(R3, [2, 3])
        circuit.add(V1, [3, 4])
        circuit.add(R4, [4, 0])
        circuit.add(I2, [0, 4])
        CCCS1.connect(R3)

        voltages, currents = solve_dc(circuit)

        assert close(currents[CCCS1], -1.5)
        assert close(currents[I1], 1.0)
        assert close(currents[I2], 3.0)
        assert close(currents[R3], -0.5)

    def test_opamp_voltage_gain_and_current_direction(self):
        circuit = Circuit()
        V1 = DCVoltageSource(1, id='V1')
        OA1 = Opamp(id='OA1')
        R1 = Resistor(1e3, id='R1')
        R2 = Resistor(1e3, id='R2')

        circuit.add(V1, [0, 1])
        circuit.add(R1, [2, 3])
        circuit.add(R2, [3, 0])
        circuit.add(OA1, [1, 3, 2])

        voltages, currents = solve_dc(circuit)

        assert close(voltages[1], 1.0)
        assert close(voltages[3], 1.0)
        assert close(voltages[2], 2.0)
        assert close(currents[OA1], 0.001)
