# Tests generated by ChatGPT. Do not edit manually.
# Not checked for correctness.

import numpy as np

from impulso import (
    Circuit,
    Resistor,
    DCVoltageSource,
    SinusoidalVoltageSource,
    Diode,
    ac_sweep,
    dc_sweep,
)


def close(value, expected, tol=1e-3):
    return np.isclose(value, expected, rtol=tol, atol=tol)


class Test_Sweep:

    def test_ac_sweep_with_diode_operating_point(self):
        circuit = Circuit()
        Vdc = DCVoltageSource(1, id='Vdc')
        Vac = SinusoidalVoltageSource(1, frequency=1000, phase=0, ac_source=True, id='Vac')
        R1 = Resistor(1e3, id='R1')
        D1 = Diode(id='D1')

        circuit.add(Vdc, [0, 1])
        circuit.add(Vac, [1, 2])
        circuit.add(R1, [2, 0])
        circuit.add(D1, [2, 0])

        results = ac_sweep(circuit, [1000, 2000])

        for frequency, (voltages, currents) in results.items():
            assert close(voltages[2], 1.0)
            assert close(currents[R1], 0.001)
            assert np.isclose(np.angle(voltages[2]), 0.0, atol=1e-6)
            assert currents[D1].real > 0
            assert currents[R1].real > 0

    def test_dc_sweep_voltage_source_over_resistor(self):
        circuit = Circuit()
        V1 = DCVoltageSource(0, id='V1')
        R1 = Resistor(1e3, id='R1')

        circuit.add(V1, [0, 1])
        circuit.add(R1, [1, 0])

        voltages, currents = dc_sweep(circuit, V1, [0, 1, 2])

        assert len(voltages) == 3
        assert len(currents) == 3

        for expected_voltage, voltage_map, current_map in zip([0, 1, 2], voltages, currents):
            assert close(voltage_map[1], expected_voltage)
            assert close(current_map[R1], expected_voltage / 1000)
            assert close(current_map[V1], expected_voltage / 1000)
