# Tests generated by ChatGPT. Do not edit manually.
# Not checked for correctness.

import numpy as np

from impulso import (
    Circuit,
    Resistor,
    Capacitor,
    Inductor,
    VCCS,
    SinusoidalCurrentSource,
    SinusoidalVoltageSource,
    solve_ac,
)


def close(value, expected, tol=1e-3):
    return np.isclose(value, expected, rtol=tol, atol=tol)


class Test_AC:

    def test_phase_and_magnitude_in_series_rl(self):
        circuit = Circuit()
        V1 = SinusoidalVoltageSource(1, frequency=1000, phase=np.pi / 4, ac_source=True, id='V1')
        R1 = Resistor(1000, id='R1')
        L1 = Inductor(1e-3, id='L1')

        circuit.add(V1, [0, 1])
        circuit.add(R1, [1, 2])
        circuit.add(L1, [2, 0])

        voltages, currents = solve_ac(circuit, 1000)
        expected = np.exp(1j * np.pi / 4) * (1j * 2 * np.pi * 1000 * 1e-3) / (
            1000 + 1j * 2 * np.pi * 1000 * 1e-3
        )

        assert close(voltages[2], expected, tol=1e-3)
        assert close(currents[R1], currents[L1], tol=1e-3)
        assert np.isclose(np.angle(voltages[2]), np.angle(expected), atol=1e-2)
        assert np.isclose(abs(voltages[2]), abs(expected), rtol=1e-3, atol=1e-6)

    def test_vccs_ac_output_matches_control_voltage(self):
        circuit = Circuit()
        V1 = SinusoidalVoltageSource(1, frequency=1000, phase=0, ac_source=True, id='V1')
        G1 = VCCS(0.001, id='G1')
        G1.connect((1, 0))
        R2 = Resistor(1000, id='R2')

        circuit.add(V1, [0, 1])
        circuit.add(G1, [2, 0, 1, 0])
        circuit.add(R2, [2, 0])

        voltages, currents = solve_ac(circuit, 1000)

        assert close(voltages[2], 1.0, tol=1e-3)
        assert close(currents[R2], 0.001, tol=1e-3)
        assert np.isclose(np.angle(voltages[2]), 0.0, atol=1e-6)
        assert np.isclose(np.angle(currents[R2]), 0.0, atol=1e-6)

    def test_sinusoidal_current_source_in_ac(self):
        circuit = Circuit()
        I1 = SinusoidalCurrentSource(0.001, phase=0, ac_source=True, id='I1')
        R1 = Resistor(1000, id='R1')

        circuit.add(I1, [1, 0])
        circuit.add(R1, [1, 0])

        voltages, currents = solve_ac(circuit, 1000)

        assert close(voltages[1], -1.0, tol=1e-3)
        assert close(currents[R1], -0.001, tol=1e-3)
        assert close(currents[I1], 0.001, tol=1e-3)
