# Tests generated by ChatGPT. Do not edit manually.
# Not checked for correctness.

import numpy as np

from impulso import (
    Circuit,
    Resistor,
    Capacitor,
    DCVoltageSource,
    DiracDeltaVoltageSource,
    solve_transient,
)


def close(value, expected, tol=1e-3):
    return np.isclose(value, expected, rtol=tol, atol=tol)


class Test_Transient:

    def test_rc_step_response_and_direction(self):
        circuit = Circuit()
        V1 = DCVoltageSource(1, id='V1')
        R1 = Resistor(1e3, id='R1')
        C1 = Capacitor(1e-6, id='C1')

        circuit.add(V1, [0, 1])
        circuit.add(R1, [1, 0])
        circuit.add(C1, [1, 0])

        times, voltages, currents = solve_transient(circuit, 5e-6, 1e-6)

        assert close(voltages[1][0], 0.0)
        assert close(voltages[1][1], 1.0)
        assert close(currents[R1][0], 0.001)
        assert close(currents[C1][0], 1.0)
        assert close(currents[C1][2], 0.0)

    def test_dirac_delta_voltage_source_impulse(self):
        circuit = Circuit()
        R1 = Resistor(1e3, id='R1')
        D1 = DiracDeltaVoltageSource(dt=1e-6, delay=0, voltage=1, id='D1')

        circuit.add(D1, [0, 1])
        circuit.add(R1, [1, 0])

        times, voltages, currents = solve_transient(circuit, 1e-6, 1e-6)

        assert close(times[0], 0.0)
        assert close(voltages[1][0], 1e6, tol=1e-6)
        assert close(currents[R1][0], 1000.0, tol=1e-6)
        assert close(currents[D1][0], 1000.0, tol=1e-6)
        assert close(currents[R1][1], 0.0)
        assert close(currents[D1][1], 0.0)
